version: "3.9"

services:
    example_project_deepak:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: example_project_deepak
        ports:
            - "80:80"
        volumes:
            - .:/app
        environment:
            - PYTHONUNBUFFERED=1
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        command: >
            example_project_deepak
