name: deploy and publish pipeline

on:
    release:
        types: [published]
        branches: [main]

env:
    DOCKER_IMAGE: deepak93p/example_project_deepak # Replace with your DockerHub image
    AZURE_WEBAPP_NAME: example-project-deepak-app # Replace with your Azure Web App name
    AZURE_WEBAPP_RG: example-project-deepak-rg # Replace with your Azure Web App name

jobs:
    build-push-docker-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              env:
                  DOCKER_USER: deepak93p
                  DOCKER_PWD: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
              run: echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

            - name: Build and Push Docker Image
              run: make docker-build-and-push IMAGE=${{ env.DOCKER_IMAGE }} TAG=${{ github.sha }}

            - name: Clean up Docker system
              run: docker system prune -f

    deploy:
        runs-on: ubuntu-latest
        needs: build-push-docker-image
        environment:
            name: "production"
            url: ${{ steps.deploy-to-webapp.outputs.fqdn }}

        steps:
            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy to Azure Container Apps
              id: deploy-to-webapp
              run: |
                  az containerapp update \
                    --name ${{ env.AZURE_WEBAPP_NAME }} \
                    --resource-group ${{ env.AZURE_WEBAPP_RG }} \
                    --image index.docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
                    --query "properties.configuration.ingress.fqdn" \
                    -o tsv

    publish-to-pypi:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4

            - name: Set up the environment
              uses: ./.github/actions/setup-poetry-env

            - name: Export tag
              id: vars
              run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

            - name: Build and publish
              run: |
                  source .venv/bin/activate
                  poetry version $RELEASE_VERSION
                  make build-and-publish
              env:
                  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
                  RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
    deploy-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4

            - name: Set up the environment
              uses: ./.github/actions/setup-poetry-env

            - name: Deploy documentation
              run: poetry run mkdocs gh-deploy --force
